### ISSUE TITLE
log module fails to import due to `ModuleNotFoundError: No module named '_testcapi'`

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#459]
**Describe the bug**
Dysh cannot be used due to an import error. 

**How to Reproduce**

```
File .../.venv/lib/python3.12/site-packages/dysh/log.py:14
     11 from pathlib import Path
     12 from typing import Callable, NewType, Union  # , Self # not available until 3.11
---> 14 import _testcapi
     15 from astropy.io.fits.header import _HeaderCommentaryCards
     16 from astropy.logger import AstropyLogger

ModuleNotFoundError: No module named '_testcapi'
```

**Environment**
- Dysh version: 0.4
- Python version: 3.12
- OS: RHEL8

**Action**

Rather than try and figure out why `_testcapi` isn't available, I think we would be better off avoiding use of it entirely. I think I have code that does this already, but not sure how to thoroughly test it -- any advice?

**Comment by mpound** [comment]
possibly this:
```
        def func_wrapper(*args, **kwargs):
            try:
                result = func(*args, **kwargs)
            except:  # remove the wrapper from the stack trace
                tp, exc, tb = sys.exc_info()
                raise  tp(exc).with_traceback(tb.tb_next)
```

**Comment by mpound** [comment]
Well, what's interesting is the whole method of removing the outer wrapper from the stacktrace no longer works in for python >3.9.     It doesn't matter if using the `_testcapi` module or `tp(exc).with_traceback`
```
from dysh.fits import GBTFITSLoad
from dysh.util import get_project_testdata
file = get_project_testdata() / "AGBT05B_047_01/AGBT05B_047_01.raw.acs/"
sdf = GBTFITSLoad(file)
sdf.summary()
x=sdf.gettp(scan=51,plnum=0)
```
Then in  dysh 0.3.0, python 3.9.13:
```
x.timeaverage(z=x)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-8663a7e94265> in <module>
----> 1 x.timeaverage(z=x)

TypeError: timeaverage() got an unexpected keyword argument 'z'

```

But in dysh 0.4.1, python 3.117, we see the `wrapper` in the traceback
```
x[0].timeaverage(z=0)
Traceback (most recent call last):

  File ~/src/dysh/src/dysh/log.py:370 in wrapper
    if hasattr(self, "_history"):

TypeError: TPScan.timeaverage() got an unexpected keyword argument 'z'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[9], line 1
    x[0].timeaverage(z=0)

  File ~/src/dysh/src/dysh/log.py:373 in wrapper
    extra = {

TypeError: TPScan.timeaverage() got an unexpected keyword argument 'z'
```

So some new method of removing the wrapper is needed.

**Comment by mpound** [comment]
there is [a package that deals with this for Python 3.9+](https://pypi.org/project/hide-from-traceback/), but it is likely not mature enough for us to depend on

**Comment by tchamberlin** [comment]
I'm not convinced that the costs outweigh the benefit here -- I know the wrappers introduce noise into the tracebacks but it's at the expense of accuracy. And maybe I'm just too used to working in frameworks where every error is 30 levels deep, but I'm not super bothered by the presence of wrapper calls

**Comment by tchamberlin** [comment]
Another thought: a common(ish) pattern I've seen is just avoiding the traceback entirely, at least in some contexts. For example in some CLIs I have, by default, simply printed the error message and then exited, so it looks more like a "standard" error message. We follow that pattern in Astrid, too, where tracebacks aren't shown at all unless a "trace" checkbox is checked.

For most use cases here I think I'd still prefer the full traceback, but... I'm not sure if an average user would? They would just want an error message they can email to somebody; they are very unlikely to ever inspect Dysh code. So "tracebacks for -v3 and above" or something might help?

**Comment by mpound** [comment]
Yes, in reviewing explanations of attempts to do this in various forums, some answers are "don't mess with the traceback."  I'm not averse to that opinion.   One thing we could do is create an issue noting the changed behavior then close with wontfix and an explanation.
